/**
 * @author Stan Permiakov
 * @version 1.0
 * @since 2025-07-28
 */
package com.stanissudo.gymlog.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.stanissudo.gymlog.database.GymLogDatabase;

import java.util.Objects;

/**
 * Represents a user in the GymLog application.
 * This entity is stored in the {@link GymLogDatabase#USER_TABLE} table.
 *  Represents a user entity for the GymLog application.
 *  This class is annotated as a Room Entity and is persisted in the USER_TABLE.
 *  It includes fields for ID, username, password, and admin status.
 * This model is used for authentication and tracking user-specific logs.
 */
@Entity(tableName = GymLogDatabase.USER_TABLE)
public class User {

    /**
     * Primary key for the user. Automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String username;
    private String password;
    private boolean isAdmin = false;

    /**
     * Constructs a new User with the given username and password.
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && isAdmin == user.isAdmin && Objects.equals(username, user.username) && Objects.equals(password, user.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username, password, isAdmin);
    }
}
